name: Checker

on:
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch:


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm, dependencies, and build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io - u ${{ github.actor }} --password-stdin
      
      - name: Docker image...
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: WebAppMy-lab-9
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
