name: Build and Publish Frontend

on:
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # Встановлення pnpm, залежностей та збірка у скрипті
      - name: Install pnpm, dependencies, and build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      # Авторизація у GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Збірка та публікація Docker-образу
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
